{"uid":"2ee9c59bdd3e831e","name":"test_contact_message_form","fullName":"tests.test_contact_message.TestContactMessageForm#test_contact_message_form","historyId":"9cb44c63571ee1264f53e4b39609c10a","time":{"start":1690364465984,"stop":1690364465984,"duration":0},"status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790","statusTrace":"E   ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1690364465985,"stop":1690364466011,"duration":26},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"browser","time":{"start":1690364466011,"stop":1690364468899,"duration":2888},"status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/UI-test-automation/UI-test-automation/conftest.py\", line 33, in browser\n    service=Service(ChromeDriverManager().install()),\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py\", line 39, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py\", line 30, in _get_driver_path\n    file = self._download_manager.download_file(driver.get_driver_download_url())\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py\", line 40, in get_driver_download_url\n    driver_version_to_download = self.get_driver_version_to_download()\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/core/driver.py\", line 51, in get_driver_version_to_download\n    self._driver_to_download_version = self._version if self._version not in (None, \"latest\") else self.get_latest_release_version()\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py\", line 62, in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 37, in get\n    self.validate_response(resp)\n  File \"/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 16, in validate_response\n    raise ValueError(f\"There is no such driver by url {resp.url}\")\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"story","value":"Тест отправления сообщения с контактами."},{"name":"feature","value":"Тесты формы отправления сообщения."},{"name":"tag","value":"contact_message_form"},{"name":"tag","value":"contact_message_tests(scope='class', autouse=True)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_contact_message"},{"name":"subSuite","value":"TestContactMessageForm"},{"name":"host","value":"fv-az451-807"},{"name":"thread","value":"2449-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_contact_message"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"15d795e7090f9b9e","reportUrl":"https://IlyaYaP.github.io/UI-test-automation/15//#testresult/15d795e7090f9b9e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55982e1bf4e3 <unknown>\n#1 0x55982deeec76 <unknown>\n#2 0x55982df17d78 <unknown>\n#3 0x55982df14029 <unknown>\n#4 0x55982df52ccc <unknown>\n#5 0x55982df5247f <unknown>\n#6 0x55982df49de3 <unknown>\n#7 0x55982df1f2dd <unknown>\n#8 0x55982df2034e <unknown>\n#9 0x55982e17f3e4 <unknown>\n#10 0x55982e1833d7 <unknown>\n#11 0x55982e18db20 <unknown>\n#12 0x55982e184023 <unknown>\n#13 0x55982e1521aa <unknown>\n#14 0x55982e1a86b8 <unknown>\n#15 0x55982e1a8847 <unknown>\n#16 0x55982e1b8243 <unknown>\n#17 0x7f2e8c273b43 <unknown>","time":{"start":1690292034668,"stop":1690292034668,"duration":0}},{"uid":"156832f12f860966","reportUrl":"https://IlyaYaP.github.io/UI-test-automation/13//#testresult/156832f12f860966","status":"passed","time":{"start":1689967871607,"stop":1689967872619,"duration":1012}}]},"tags":["contact_message_form","contact_message_tests(scope='class', autouse=True)"]},"source":"2ee9c59bdd3e831e.json","parameterValues":[]}